package com.example.yogeshwar.rentalplatform;

import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;
import android.os.Environment;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import org.w3c.dom.Document;

import java.io.File;
import java.io.FileOutputStream;

public class last extends AppCompatActivity {

    DatabaseReference db;
    int m;
    Bundle d;
    book_details b;
    Button button;
    String s[];
    TextView t3,t5,t7,t8;
    private String filename;
    private String filepath = "MyFileStorage";
    File myExternalFile;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_last);
        Bundle c=getIntent().getExtras();
        d=c.getBundle("pck");
        s=d.getStringArray("cdnt");

        button=(Button)findViewById(R.id.button);
        m=Integer.parseInt(s[6]);
        t3=(TextView)findViewById(R.id.t3);
        t3.setText(s[3]);
        filename=""+s[3]+".pdf";
        myExternalFile = new File(getExternalFilesDir(filepath), filename);
        t5=(TextView)findViewById(R.id.t5);
        t5.setText(s[2]);
        t7=(TextView)findViewById(R.id.t7);
        if(m==0)
            t7.setText("Book");
        else
            t7.setText("DVD");
        t8=(TextView)findViewById(R.id.t8);


    }

    public void dr(View view){

        if(m==0)
            db = FirebaseDatabase.getInstance().getReference().child("book").child(s[5]);
        else if(m==1)
            db = FirebaseDatabase.getInstance().getReference().child("dvd").child(s[5]);

        db.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {

                for(DataSnapshot i:dataSnapshot.getChildren()){
                    b=i.getValue(book_details.class);
                    if(b.getBname().equals(s[3])){
                        b.nc=b.nc-1;
                        db.child(i.getKey()).setValue(b);
                        createpdf();
                        t8.setText("DONE.............");

                        button.setVisibility(View.GONE);
                        break;
                    }
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });


    }

    public void createpdf() {

        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT) {
            PdfDocument document = new PdfDocument();

            PdfDocument.PageInfo pageInfo =
                    new PdfDocument.PageInfo.Builder(100, 100, 1).create();

            // start a page
            PdfDocument.Page page = document.startPage(pageInfo);

            Paint paint = new Paint();


            paint.setColor(Color.RED);
            paint.setTextSize(4);

            Canvas canvas = page.getCanvas();


            paint.setColor(Color.BLACK);

            String src="*****************************";
            canvas.drawText(src,10,15,paint);
            src="This is a machine generated receipt.";
            canvas.drawText(src,10,20,paint);
            src="Generated by The Rental Platform App";
            canvas.drawText(src,10,25,paint);
            src="Item name: "+s[3];
            canvas.drawText(src,10,30,paint);
            src="Item type: "+t7.getText();
            canvas.drawText(src,10,35,paint);
            src="Price: "+s[2];
            canvas.drawText(src,10,40,paint);
            src="Location: "+s[0]+","+s[1];
            canvas.drawText(src,10,45,paint);

            src="*****************************";
            canvas.drawText(src,10,60,paint);
            // finish the page
            document.finishPage(page);
            try{
                FileOutputStream fos = new FileOutputStream(myExternalFile);
                document.writeTo(fos);
                Toast.makeText(this, "Done", Toast.LENGTH_LONG).show();

            }
            catch(Exception e)
            {
                e.printStackTrace();
            }




        }
    }

}
